name: jingen_batteryutils_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  jnigen: ^0.2.0
  jni: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
